# cotire.cmake 1.8.0 generated file
# /Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/libs/base/wxbase_C_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/build/cmake/modules/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "wxbase_EXPORTS;WXBUILDING;_LIB;wxUSE_GUI=0;wxUSE_BASE=1;_UNICODE;__WXOSX_COCOA__;__WXMAC__;__WXOSX__;DLL_EXPORTS;WXMAKINGDLL_BASE;WX_PRECOMP")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "-g;-Wall;-Wno-ignored-attributes;-pthread;-fPIC;-isysroot;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug")
set (COTIRE_TARGET_C_COMPILER_LAUNCHER "COTIRE_TARGET_C_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/Users/frank/Documents/Code/C++/CMakeTest")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_DEBUG "/opt/local/include;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/regex;/Users/frank/Documents/Code/C++/CMakeTest/lib/wx/include/osx_cocoa-unicode-3.1;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/include")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "C")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/common/extended.c")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Debug")
set (CMAKE_C_COMPILER_ID "AppleClang")
set (CMAKE_C_COMPILER_VERSION "12.0.0.12000032")
set (CMAKE_C_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc")
set (CMAKE_C_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_C "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_C "-isystem ")
set (CMAKE_C_FRAMEWORK_SEARCH_FLAG "-F")
set (CMAKE_C_SYSTEM_FRAMEWORK_SEARCH_FLAG "-iframework ")
set (CMAKE_C_SOURCE_FILE_EXTENSIONS "c;m")
