# cotire.cmake 1.8.0 generated file
# /Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/libs/xrc/wxxrc_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/build/cmake/modules/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "wxxrc_EXPORTS;WXBUILDING;_LIB;wxUSE_GUI=1;wxUSE_BASE=0;_UNICODE;__WXOSX_COCOA__;__WXMAC__;__WXOSX__;DLL_EXPORTS;WXMAKINGDLL_XRC;WXUSINGDLL;WX_PRECOMP")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "-g;-Wall;-Wno-ignored-attributes;-pthread;-std=gnu++17;-fPIC;-isysroot;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/Users/frank/Documents/Code/C++/CMakeTest")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_DEBUG "/Users/frank/Documents/Code/C++/CMakeTest/lib/wx/include/osx_cocoa-unicode-3.1;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/include")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_activityindicator.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_animatctrl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_bannerwindow.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_bmp.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_bmpcbox.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_bmpbt.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_bttn.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_cald.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_chckb.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_chckl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_choic.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_choicbk.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_clrpicker.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_cmdlinkbn.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_collpane.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_combo.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_comboctrl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_datectrl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_dirpicker.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_dlg.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_editlbox.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_filectrl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_filepicker.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_fontpicker.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_frame.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_gauge.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_gdctl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_grid.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_html.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_hyperlink.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_infobar.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_listb.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_listbk.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_listc.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_mdi.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_menu.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_notbk.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_odcombo.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_panel.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_propdlg.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_radbt.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_radbx.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_scrol.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_scwin.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_htmllbox.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_simplebook.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_sizer.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_slidr.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_spin.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_split.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_srchctrl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_statbar.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_stbmp.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_stbox.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_stlin.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_sttxt.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_text.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_tglbtn.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_timectrl.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_toolb.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_toolbk.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_tree.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_treebk.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_unkwn.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_wizrd.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xmlres.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xmlrsall.cpp;/Users/frank/Documents/Code/C++/CMakeTest/lib/wxWidgets-3.1.4/src/xrc/xh_dataview.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Debug")
set (CMAKE_CXX_COMPILER_ID "AppleClang")
set (CMAKE_CXX_COMPILER_VERSION "12.0.0.12000032")
set (CMAKE_CXX_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_FRAMEWORK_SEARCH_FLAG "-F")
set (CMAKE_CXX_SYSTEM_FRAMEWORK_SEARCH_FLAG "-iframework ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
